config_name: config_color
saved_data_root: data/weights

seed: 2
n_splits: 10
decode_from: eeg

# ==== preproc ==== #  
dura_unit: 1.25 # sec
no_avg: false  # default: false
n_trial_avg: 5
n_ch_eeg: 128
n_ch_noise: 3
unit_coeff: 1.0e-6
preamp_gain : 10
jitter: 0.1 # sec
nlms:
  mu: 0.1
  w: random
  # n_jobs: 16
bandpass:
  low: 2.
  high: 118.
car: true  # common average reference
notch_filter: true
bandpass_filter:
  lower_band: 2
  upper_band: 118
emg_highpass:
  apply: false
  low: 60
  high: 127
wo_adapt_filt: false # default: false
  
# ==== Architecture ==== #
model_name: EEGNet
# common
num_channels: 128
n_class: 5
k1: 30 # 960
k2: 4 # 96
F1: 16
F2: 32
D: 2
p1: 2 # 40
p2: 4 # 80
dr1: 0.50
dr2: 0.75
hilbert_transform: False
# for with mask
### for 10-20
channels_use:
  - 4  # T7
  - 17  # C5
  - 39  # CP5
  - 49  # FT7
  - 60  # FC5
  - 67  # F7
  - 78  # F5
  - 92  # F3
  - 104  # FC3
  - 117  # FC1
# for RNN
rnn_type: LSTM
hidden_size: 128
num_layers: 2
bidirectional: True
dropout_rate: 0.5
last_activation: softmax
# for CovTanSVM
C: 1.6653738245684553 # optimized by optuna

# ==== Training ==== #
save_results: True
normalize: false
n_epochs: 1000
optimizer: AdamW
learning_rate: 1.0e-4
eps: 1.0e-8
weight_decay: 0.01
scheduler:
  apply: False
  name: CosineAnnealingLR # CosineAnnealingLR | ReduceLROnPlateau
  factor: 0.1
  patience: 10
  Tmax: 100
lr_divide: 10.0
batch_size: 16
n_worekers: 0
save_best:
  apply: True
  monitor: loss_val
log_inference: True
test_ratio: 0.1
ensemble_methods: 
  - mean
  - max
  - zscore_mean
  - zscore_max
  - entropy_weighted
  - inverse_entropy_weighted
  - majority

parallel_sets: subject1-min-overt_covert
subject1-min-overt_covert:
  csv_dir: data/subject1/min-overt_covert
  npy_dir: data/subject1/min-overt_covert/eeg_margin_before_preproc/train
  csv_header: _min-overt_covert_train
  gpu: 0
subject1-overt_covert:
  csv_dir: data/subject1/overt_covert
  npy_dir: data/subject1/overt_covert/eeg_margin_before_preproc/train
  csv_header: _overt_covert_train
  gpu: 1
subject1-overt_min-overt_covert:
  csv_dir: data/subject1/overt_min-overt_covert
  npy_dir: data/subject1/overt_min-overt_covert/eeg_margin_before_preproc/train
  csv_header: _overt_min-overt_covert_train
  gpu: 2
subject2-min-overt_covert:
  csv_dir: data/subject2/min-overt_covert
  npy_dir: data/subject2/min-overt_covert/eeg_margin_before_preproc/train
  csv_header: _min-overt_covert_train
  gpu: 3
subject2-overt_covert:
  csv_dir: data/subject2/overt_covert
  npy_dir: data/subject2/overt_covert/eeg_margin_before_preproc/train
  csv_header: _overt_covert_train
  gpu: 4
subject2-overt_min-overt_covert:
  csv_dir: data/subject2/overt_min-overt_covert
  npy_dir: data/subject2/overt_min-overt_covert/eeg_margin_before_preproc/train
  csv_header: _overt_min-overt_covert_train
  gpu: 0
subject3-min-overt_covert:
  csv_dir: data/subject3/min-overt_covert
  npy_dir: data/subject3/min-overt_covert/eeg_margin_before_preproc/train
  csv_header: _min-overt_covert_train
  gpu: 1
subject3-overt_covert:
  csv_dir: data/subject3/overt_covert
  npy_dir: data/subject3/overt_covert/eeg_margin_before_preproc/train
  csv_header: _overt_covert_train
  gpu: 2
subject3-overt_min-overt_covert:
  csv_dir: data/subject3/overt_min-overt_covert
  npy_dir: data/subject3/overt_min-overt_covert/eeg_margin_before_preproc/train
  csv_header: _overt_min-overt_covert_train
  gpu: 3
# covert first
subject1-covert_overt:
  csv_dir: data/subject1/covert_overt
  npy_dir: data/subject1/covert_overt/eeg_margin_before_preproc/train
  csv_header: _covert_overt_train
  gpu: 4
subject1-covert_min-overt:
  csv_dir: data/subject1/covert_min-overt
  npy_dir: data/subject1/covert_min-overt/eeg_margin_before_preproc/train
  csv_header: _covert_min-overt_train
  gpu: 0
subject2-covert_overt:
  csv_dir: data/subject2/covert_overt
  npy_dir: data/subject2/covert_overt/eeg_margin_before_preproc/train
  csv_header: _covert_overt_train
  gpu: 1
subject2-covert_min-overt:
  csv_dir: data/subject2/covert_min-overt
  npy_dir: data/subject2/covert_min-overt/eeg_margin_before_preproc/train
  csv_header: _covert_min-overt_train
  gpu: 2
subject3-covert_overt:
  csv_dir: data/subject3/covert_overt
  npy_dir: data/subject3/covert_overt/eeg_margin_before_preproc/train
  csv_header: _covert_overt_train
  gpu: 3
subject3-covert_min-overt:
  csv_dir: data/subject3/covert_min-overt
  npy_dir: data/subject3/covert_min-overt/eeg_margin_before_preproc/train
  csv_header: _covert_min-overt_train
  gpu: 4


fs : 256

# Hydra options
use_hydra_savedir: True
hydra:
  job:
    chdir: True
  sweep:
    dir: 'outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}'
    subdir: '${hydra.job.override_dirname}'